# Generated by Django 5.2.8 on 2025-11-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journey",
            options={"ordering": ("departure_time",)},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("created_at",)},
        ),
    ]
