# Generated by Django 5.2.8 on 2025-11-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0003_alter_journey_options_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(
                fields=["departure_time"], name="railway_jou_departu_0ec88b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["source", "destination"], name="railway_rou_source__9b1b4f_idx"
            ),
        ),
    ]
