# Generated by Django 5.2.8 on 2025-11-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0004_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
